Support for localization
tombarton/botbuilder-forms pull request #1
Opened 2017-06-25 01:07 UTC by User1m

- added support for localization

2017-06-25 01:07 UTC, User1m commented
@liliankasem @tombarton

2017-06-25 08:52 UTC, tombarton commented
Hi @User1m, thank you so much for your contribution. It looks fantastic. My only request is to bring your changes inline with [Standard JS](https://standardjs.com/) formatting. I've updated the testing scripts to include standard, hence why the build is now failing.

2017-06-25 13:45 UTC, tombarton requested changes

2017-06-25 13:45 UTC, tombarton commented on index.js
> +                builder.Prompts.confirm(session, session.localizer.gettext(session.preferredLocale(), prompt))
I'm not 100% sure about this. I'm not too familiar with the localiser functions, but from what I've read it goes and fetches a string from a separate JSON file. The prompt variable here is being built from the question object that is fed into the module. If you wanted to go multilingual, wouldn't you fetch the different language version on line 27 before you add the entity data into the string?

I should be able to take a look into this in more detail on Monday.

2017-06-27 15:58 UTC, user1m reviewed
Using `standard --fix` and fixed entities issue

2017-06-27 15:58 UTC, User1m commented on index.js
> +                builder.Prompts.confirm(session, session.localizer.gettext(session.preferredLocale(), prompt))
You're right. I wasn't sure what you were doing here at first but after looking closer I see you're replacing a placeholder variable with some user content. Pushed the change :)

2017-06-27 16:06 UTC, User1m commented
@tombarton changes made

2017-06-27 16:07 UTC, tombarton commented
Perfect, thanks @User1m. I'll review tonight.

2017-07-19 23:33 UTC, User1m commented
ping @tombarton

2017-07-20 11:53 UTC, tombarton commented
Sorry @User1m, it's been a hectic couple of weeks. I'll make sure I review this in the next couple of days.

2017-07-23 18:14 UTC, tombarton commented
Hi @User1m, I've been testing your contributions and they look good to me. I'm going to merge them into the `develop` branch and they will form part of the next release. Thank you for your contributions!

2017-07-23 18:15 UTC, tombarton approved these changes

2017-07-23 18:15 UTC, merged